application: cssi-decades-project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

<<<<<<< HEAD
- url: /resources
  static_dir: static_folder
=======
- url: .*
  script: main.app
>>>>>>> ba8a18f44ca3ce2e75c010cdb0514cde3c296976

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
